/* global instantsearch, algoliasearch, CONFIG */
document.addEventListener("DOMContentLoaded",()=>{const e=CONFIG.algolia,{indexName:a,appID:t,apiKey:s}=e;let i=instantsearch({indexName:a,searchClient:algoliasearch(t,s),searchFunction:e=>{document.querySelector(".search-input").value&&e.search()}});window.pjax&&i.on("render",()=>{window.pjax.refresh(document.getElementById("algolia-hits"))}),
// Registering Widgets
i.addWidgets([instantsearch.widgets.configure({hitsPerPage:e.hits.per_page||10}),instantsearch.widgets.searchBox({container:".search-input-container",placeholder:e.labels.input_placeholder,
// Hide default icons of algolia search
showReset:!1,showSubmit:!1,showLoadingIndicator:!1,cssClasses:{input:"search-input"}}),instantsearch.widgets.stats({container:"#algolia-stats",templates:{text:a=>`${e.labels.hits_stats.replace(/\$\{hits}/,a.nbHits).replace(/\$\{time}/,a.processingTimeMS)}\n            <span class="algolia-powered">\n              <img src="${CONFIG.root}images/algolia_logo.svg" alt="Algolia">\n            </span>\n            <hr>`}}),instantsearch.widgets.hits({container:"#algolia-hits",templates:{item:e=>`<a href="${e.permalink?e.permalink:CONFIG.root+e.path}" class="algolia-hit-item-link">${e._highlightResult.title.value}</a>`,empty:a=>`<div id="algolia-hits-empty">\n              ${e.labels.hits_empty.replace(/\$\{query}/,a.query)}\n            </div>`},cssClasses:{item:"algolia-hit-item"}}),instantsearch.widgets.pagination({container:"#algolia-pagination",scrollTo:!1,showFirst:!1,showLast:!1,templates:{first:'<i class="fa fa-angle-double-left"></i>',last:'<i class="fa fa-angle-double-right"></i>',previous:'<i class="fa fa-angle-left"></i>',next:'<i class="fa fa-angle-right"></i>'},cssClasses:{list:["pagination","algolia-pagination"],item:"pagination-item",link:"page-number",selectedItem:"current",disabledItem:"disabled-item"}})]),i.start(),
// Handle and trigger popup window
document.querySelectorAll(".popup-trigger").forEach(e=>{e.addEventListener("click",()=>{document.body.style.overflow="hidden",document.querySelector(".search-pop-overlay").classList.add("search-active"),document.querySelector(".search-input").focus()})});
// Monitor main search box
const l=()=>{document.body.style.overflow="",document.querySelector(".search-pop-overlay").classList.remove("search-active")};document.querySelector(".search-pop-overlay").addEventListener("click",e=>{e.target===document.querySelector(".search-pop-overlay")&&l()}),document.querySelector(".popup-btn-close").addEventListener("click",l),document.addEventListener("pjax:success",l),window.addEventListener("keyup",e=>{"Escape"===e.key&&l()})});